# 証明書作成時のみ使用するyml

version: "3.8"
networks:
  nginx_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24

volumes:
  html:
    external: true

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: web_server
    networks:
      nginx_net:
        ipv4_address: 172.16.0.9
    ports:
      - "50000:80"
      # - "50001:80"
    volumes:
      - ./html:/usr/share/nginx/html

  nginx_proxy:
    build:
      context: ./nginx_proxy
      dockerfile: Dockerfile
    container_name: reverse_proxy_server
    networks:
      - nginx_net
      - app_net
    depends_on:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # HTTPS用の証明書とキーをホストOSからゲストOSに連結する
      - /etc/letsencrypt:/etc/letsencrypt
      - html:/usr/share/nginx/html
    restart: always

  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      #取得したssl証明書を配置
      - /etc/letsencrypt:/etc/letsencrypt
      - html:/usr/share/nginx/html
    depends_on:
      - nginx_proxy
    # 10日おきに証明書を更新する(期限切れまで30日以上あれば更新しない)
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"
    command: ["--version"]
    restart: always


